# booking endpoints
GET http://localhost:8081/booking/yet
###
GET http://localhost:8081/booking/tech/mohamed
###
PUT http://localhost:8081/booking/update
Content-Type: application/json

{
    "bookingId": 3,
    "bookedBy": "razzaksr",
    "technician": "mohamed",
    "scheduledDateTime": "2025-03-09T14:00:00",
    "service": 3,
    "status": "DONE"
}
###
GET http://localhost:8081/booking/
###
POST http://localhost:8081/booking/confirm/razzaksr/2025-03-09T14:00:00/3

###
# User endpoints
GET http://localhost:8081/users/customer
###
POST http://localhost:8081/users/signup
Content-Type: application/json

{
    "mobile":9677520692,
    "username":"razzaksr",
    "fullName":"Razak Mohamed S",
    "role":"customer",
    "latitude":11.6628047,
    "longitude":78.1680085,
    "password":"mohamed",
    "email":"razzaksr@gmail.com"
}
###
# Availability endpoint

GET http://localhost:8081/avail/

###
POST http://localhost:8081/avail/update/mohamed/2025-03-09T12:13:00/2025-03-09T16:13:00

###
# {
#   "name": "Test",
#   "timestamp": "2025-03-06T16:13:00"
# }

###

###
# Service Endpoints
DELETE http://localhost:8081/service/del/2
###
PUT http://localhost:8081/service/update
Content-Type: application/json

{
    "serviceId":3,
    "serviceName":"AC Wiring",
    "price":150
}
###
GET http://localhost:8081/service/
###
GET http://localhost:8081/service/3
###
POST http://localhost:8081/service/
Content-Type: application/json

{
    "serviceName":"AC Wiring",
    "price":100
}